#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 Claude Code PM - Project Management System"
echo "============================================="
echo ""
echo "🎯 Quick Start Workflow"
echo "  1. /pm:constitution-create   - Establish project standards (optional)"
echo "  2. /pm:prd-new <name>        - Create a new PRD"
echo "  3. /pm:prd-parse <name>      - Convert PRD to epic"
echo "  4. /pm:epic-decompose <name> - Break into tasks"
echo "  5. /pm:epic-sync <name>      - Push to Gitea"
echo "  6. /pm:epic-start <name>     - Start parallel execution"
echo ""
echo "📐 Spec-Driven Development"
echo "  /pm:constitution-create    - Create project constitution (standards)"
echo "  /pm:spec-validate <name>   - Validate epic meets specification"
echo ""
echo "📄 PRD Commands"
echo "  /pm:prd-new <name>     - Launch brainstorming for new product requirement"
echo "  /pm:prd-parse <name>   - Convert PRD to implementation epic"
echo "  /pm:prd-list           - List all PRDs"
echo "  /pm:prd-edit <name>    - Edit existing PRD"
echo "  /pm:prd-status         - Show PRD implementation status"
echo ""
echo "📚 Epic Commands"
echo "  /pm:epic-decompose <name> - Break epic into task files"
echo "  /pm:epic-sync <name>      - Push epic and tasks to Gitea"
echo "  /pm:epic-oneshot <name>   - Decompose and sync in one command"
echo "  /pm:epic-list             - List all epics"
echo "  /pm:epic-show <name>      - Display epic and its tasks"
echo "  /pm:epic-status [name]    - Show epic progress"
echo "  /pm:epic-close <name>     - Mark epic as complete"
echo "  /pm:epic-edit <name>      - Edit epic details"
echo "  /pm:epic-refresh <name>   - Update epic progress from tasks"
echo "  /pm:epic-start <name>     - Launch parallel agent execution"
echo ""
echo "📝 Issue Commands"
echo "  /pm:issue-show <num>      - Display issue and sub-issues"
echo "  /pm:issue-status <num>    - Check issue status"
echo "  /pm:issue-start <num>     - Begin work with specialized agent"
echo "  /pm:issue-sync <num>      - Push updates to Gitea"
echo "  /pm:issue-close <num>     - Mark issue as complete"
echo "  /pm:issue-reopen <num>    - Reopen closed issue"
echo "  /pm:issue-edit <num>      - Edit issue details"
echo "  /pm:issue-analyze <num>   - Analyze for parallel work streams"
echo ""
echo "🔄 Workflow Commands"
echo "  /pm:next               - Show next priority tasks"
echo "  /pm:status             - Overall project dashboard"
echo "  /pm:standup            - Daily standup report"
echo "  /pm:blocked            - Show blocked tasks"
echo "  /pm:in-progress        - List work in progress"
echo ""
echo "🔗 Sync Commands"
echo "  /pm:sync               - Full bidirectional sync with Gitea"
echo "  /pm:import <issue>     - Import existing Gitea issues"
echo ""
echo "🔧 Maintenance Commands"
echo "  /pm:validate           - Check system integrity"
echo "  /pm:clean              - Archive completed work"
echo "  /pm:search <query>     - Search across all content"
echo ""
echo "⚙️  Setup Commands"
echo "  /pm:init               - Install dependencies and configure Gitea"
echo "  /pm:help               - Show this help message"
echo ""
echo "💡 Tips"
echo "  • Start with: /pm:constitution-create (optional but recommended)"
echo "  • Use /pm:next to find available work"
echo "  • Run /pm:status for quick overview"
echo "  • Validate before merge: /pm:spec-validate <name>"
echo "  • Epic workflow: prd-new → prd-parse → epic-decompose → epic-sync"
echo "  • View README.md for complete documentation"

exit 0
